logging:
  level:
    cc:
      vivp:
        bankrupt: DEBUG
    root: INFO

server:
  port: 58090

spring:
  application:
    name: service-transaction-management
  datasource:
    password: bankrupt
    testWhileIdle: true
    url: jdbc:mysql://0.0.0.0:3306/bankrupt?useSSL=false
    username: root
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    default-property-inclusion: NON_NULL

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761