logging:
  level:
    cc:
      vivp:
        bankrupt: DEBUG
    root: INFO

server:
  port: 58080

spring:
  application:
    name: service-payment-producer
  datasource:
    password: bankrupt
    testWhileIdle: true
    url: jdbc:mysql://0.0.0.0:3306/bankrupt?useSSL=false
    username: root
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    default-property-inclusion: NON_NULL
  kafka:
    bootstrap-servers: 0.0.0.0:9092

kafka:
  payments:
    topic-name: payments-topic

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761

service-payment-producer:
  ribbon:
    listOfServers:
      - http://localhost:58080