logging:
  level:
    cc:
      vivp:
        bankrupt: DEBUG
    root: INFO

server:
  port: 48080

spring:
  application:
    name: worker-payment-consumer
  datasource:
    password: bankrupt
    testWhileIdle: true
    url: jdbc:mysql://0.0.0.0:3306/bankrupt?useSSL=false
    username: root
    validationQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  kafka:
    bootstrap-servers: 0.0.0.0:9092
    consumer:
      group-id: payments-group

kafka:
  payments:
    topic-name: payments-topic